server:
  port: 8888

spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:http://localhost:9999"
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecom-realm

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: lb://CUSTOMER-SERVICE
              predicates:
                  - Path=/api/customers/**

            - id: r2
              uri: lb://INVENTORY-SERVICE
              predicates:
                  - Path=/api/products/**

            - id: r3
              uri: lb://BILLING-SERVICE
              predicates:
                  - Path=/api/bills/**

            - id: r4
              uri: lb://CHATBOT-SERVICE
              predicates:
                  - Path=/api/chatbot/**
